### PR TITLE
usage cost page using tab styling

### PR DESCRIPTION
**Pull request by irfanpule**
Hi @setyongr, please review.

I'm adding new style usage cost page without delete existing class and template.

Screenshot
Screenshot 2023-05-16 at 11 30 41

Download Results
[usage_cost (3).pdf](https://github.com/Yuyu-billing/yuyu_dashboard/files/11484030/usage_cost.3.pdf)

### CODE REVIEW

**Comment by setyongr** [comment]
Good work @irfanpule !

After i see your work, I notice that it only update the `Project` side of `Usage Cost`. 

How about also adding this change to the `Admin` side of `Usage Cost` that can be accessed from `Admin` -> `Billing` -> `Project Invoice`?

**Comment by irfanpule** [comment]
> Good work @irfanpule !
> 
> After i see your work, I notice that it only update the `Project` side of `Usage Cost`.
> 
> How about also adding this change to the `Admin` side of `Usage Cost` that can be accessed from `Admin` -> `Billing` -> `Project Invoice`?

Ok, i will do it

**Comment by irfanpule** [comment]
@setyongr I have done it.

Screenshot 2023-05-16 at 14 31 30
Screenshot 2023-05-16 at 14 33 29

[usage_cost (5).pdf](https://github.com/Yuyu-billing/yuyu_dashboard/files/11485239/usage_cost.5.pdf)

**Comment by setyongr** [comment]
Nice work @irfanpule !

**Pull request merged**
